services:
  stats-server:
    build: stats-svc/stats-server
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - TZ=Europe/Moscow
    networks:
      - backend

  stats-db:
    image: postgres:16.1
    container_name: stats-db-container
    ports:
      - "5435:5432"  # для DBeaver
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
    networks:
      - backend

  ewm-svc:
    build: main-svc
    container_name: ewm-svc-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - CLIENT_URL=http://stats-svc:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - TZ=Europe/Moscow
    networks:
      - backend

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db-container
    ports:
      - "5436:5432"  # для DBeaver
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
    networks:
      - backend

networks:
  backend: